// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: vcuda.proto

package vcuda

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VDeviceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusId         string `protobuf:"bytes,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	PodUid        string `protobuf:"bytes,2,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	ContainerName string `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ContainerId   string `protobuf:"bytes,4,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
}

func (x *VDeviceRequest) Reset() {
	*x = VDeviceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcuda_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VDeviceRequest) ProtoMessage() {}

func (x *VDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vcuda_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VDeviceRequest.ProtoReflect.Descriptor instead.
func (*VDeviceRequest) Descriptor() ([]byte, []int) {
	return file_vcuda_proto_rawDescGZIP(), []int{0}
}

func (x *VDeviceRequest) GetBusId() string {
	if x != nil {
		return x.BusId
	}
	return ""
}

func (x *VDeviceRequest) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *VDeviceRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *VDeviceRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type VDeviceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VDeviceResponse) Reset() {
	*x = VDeviceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vcuda_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VDeviceResponse) ProtoMessage() {}

func (x *VDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vcuda_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VDeviceResponse.ProtoReflect.Descriptor instead.
func (*VDeviceResponse) Descriptor() ([]byte, []int) {
	return file_vcuda_proto_rawDescGZIP(), []int{1}
}

var File_vcuda_proto protoreflect.FileDescriptor

var file_vcuda_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x76, 0x63, 0x75, 0x64, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76,
	0x63, 0x75, 0x64, 0x61, 0x22, 0x8a, 0x01, 0x0a, 0x0e, 0x56, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x75, 0x73, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x75, 0x73, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x70, 0x6f, 0x64, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x6f, 0x64, 0x55, 0x69, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x11, 0x0a, 0x0f, 0x56, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0x52, 0x0a, 0x0c, 0x56, 0x43, 0x55, 0x44, 0x41, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x56, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x15, 0x2e, 0x76, 0x63, 0x75, 0x64, 0x61, 0x2e,
	0x56, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x76, 0x63, 0x75, 0x64, 0x61, 0x2e, 0x56, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x76, 0x63,
	0x75, 0x64, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vcuda_proto_rawDescOnce sync.Once
	file_vcuda_proto_rawDescData = file_vcuda_proto_rawDesc
)

func file_vcuda_proto_rawDescGZIP() []byte {
	file_vcuda_proto_rawDescOnce.Do(func() {
		file_vcuda_proto_rawDescData = protoimpl.X.CompressGZIP(file_vcuda_proto_rawDescData)
	})
	return file_vcuda_proto_rawDescData
}

var file_vcuda_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vcuda_proto_goTypes = []interface{}{
	(*VDeviceRequest)(nil),  // 0: vcuda.VDeviceRequest
	(*VDeviceResponse)(nil), // 1: vcuda.VDeviceResponse
}
var file_vcuda_proto_depIdxs = []int32{
	0, // 0: vcuda.VCUDAService.RegisterVDevice:input_type -> vcuda.VDeviceRequest
	1, // 1: vcuda.VCUDAService.RegisterVDevice:output_type -> vcuda.VDeviceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vcuda_proto_init() }
func file_vcuda_proto_init() {
	if File_vcuda_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vcuda_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VDeviceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vcuda_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VDeviceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vcuda_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vcuda_proto_goTypes,
		DependencyIndexes: file_vcuda_proto_depIdxs,
		MessageInfos:      file_vcuda_proto_msgTypes,
	}.Build()
	File_vcuda_proto = out.File
	file_vcuda_proto_rawDesc = nil
	file_vcuda_proto_goTypes = nil
	file_vcuda_proto_depIdxs = nil
}
